#!/usr/bin/env python3
"""Generate the manuscript's invalid-input summary table and source CSV."""

import csv
import os
import statistics
from collections import defaultdict


from artifact_paths import RESULT_ROOT, IMG_DIR
RESULTS_DIR = os.path.join(RESULT_ROOT, "benchmark_csv_invalid")
OUTPUT_TEX = os.path.join(IMG_DIR, "invalidRuntimeTable.tex")
OUTPUT_CSV = os.path.join(
    RESULT_ROOT, "analysis", "invalid_runtime_summary.csv"
)

PARSERS = ["Leo", "GLL", "RNGLR", "BRNGLR"]
DISPLAY = {
    "Leo": "Earley",
    "GLL": "GLL",
    "RNGLR": "RNGLR",
    "BRNGLR": "BRNGLR",
}


def read_all_rows():
    rows = []
    for filename in sorted(os.listdir(RESULTS_DIR)):
        if filename.endswith(".csv"):
            with open(os.path.join(RESULTS_DIR, filename), newline="") as handle:
                rows.extend(csv.DictReader(handle))
    return rows


def successful_rejection(row):
    return (
        row.get("status", "OK") == "OK"
        and row.get("recognized", "false") == "false"
        and row.get("reject_correct", "true") == "true"
    )


def fmt(value):
    if value < 1:
        return f"{value:.3f}"
    if value < 10:
        return f"{value:.2f}"
    if value < 100:
        return f"{value:.1f}"
    return f"{value:.0f}"


def summarize(rows):
    by_parser = defaultdict(list)
    for row in rows:
        if row["parser"] in PARSERS:
            by_parser[row["parser"]].append(row)

    summaries = {}
    for parser in PARSERS:
        attempted = by_parser[parser]
        completed = [row for row in attempted if successful_rejection(row)]
        times = sorted(float(row["median_time_ns"]) / 1_000_000 for row in completed)
        if not times:
            raise ValueError(f"{parser}: no successful rejection measurements")
        q1, _, q3 = statistics.quantiles(times, n=4)
        summaries[parser] = {
            "median_ms": statistics.median(times),
            "q1_ms": q1,
            "q3_ms": q3,
            "max_ms": max(times),
            "max_mem_mb": max(
                int(row["peak_memory_bytes"]) for row in completed
            )
            / (1024 * 1024),
            "timeouts": sum(row.get("status") == "TIMEOUT" for row in attempted),
            "attempted": len(attempted),
            "completed": len(completed),
        }
    return summaries


def decorate(text, numeric_value, best, worst):
    if numeric_value == best and best != worst:
        return r"\best{" + text + "}"
    if numeric_value == worst and best != worst:
        return r"\worst{" + text + "}"
    return text


def write_csv(summaries):
    fields = [
        "parser",
        "median_ms",
        "q1_ms",
        "q3_ms",
        "max_ms",
        "max_mem_mb",
        "timeouts",
        "attempted",
        "completed",
    ]
    os.makedirs(os.path.dirname(OUTPUT_CSV), exist_ok=True)
    with open(OUTPUT_CSV, "w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for parser in PARSERS:
            writer.writerow({"parser": DISPLAY[parser], **summaries[parser]})


def write_tex(summaries):
    metrics = {
        "median_ms": {parser: summaries[parser]["median_ms"] for parser in PARSERS},
        "max_ms": {parser: summaries[parser]["max_ms"] for parser in PARSERS},
        "max_mem_mb": {
            parser: summaries[parser]["max_mem_mb"] for parser in PARSERS
        },
        "timeouts": {parser: summaries[parser]["timeouts"] for parser in PARSERS},
    }
    extrema = {
        name: (min(values.values()), max(values.values()))
        for name, values in metrics.items()
    }

    lines = [
        r"\small",
        r"% Generated by script/make_invalid_table.py -- do not edit by hand.",
        r"% Caption and label live in the main .tex file.",
        r"\begin{tabular}{|l|r|r|r|r|r|}",
        r"  \hline",
        r"  \textbf{Parser} & \textbf{Median (\millisecond)} & \textbf{IQR (\millisecond)} & \textbf{Max (\millisecond)} & \textbf{Max Mem (MB)} & \textbf{Timeouts} \\",
        r"  \hline\hline",
    ]

    for parser in PARSERS:
        summary = summaries[parser]
        median_text = fmt(summary["median_ms"])
        max_text = fmt(summary["max_ms"])
        memory_text = fmt(summary["max_mem_mb"])
        timeout_text = f"{summary['timeouts']}/{summary['attempted']}"
        median_text = decorate(
            median_text, summary["median_ms"], *extrema["median_ms"]
        )
        max_text = decorate(max_text, summary["max_ms"], *extrema["max_ms"])
        memory_text = decorate(
            memory_text, summary["max_mem_mb"], *extrema["max_mem_mb"]
        )
        timeout_text = decorate(
            timeout_text, summary["timeouts"], *extrema["timeouts"]
        )
        iqr_text = f"[{fmt(summary['q1_ms'])}, {fmt(summary['q3_ms'])}]"
        lines.append(
            f"  {DISPLAY[parser]} & {median_text} & {iqr_text} & "
            f"{max_text} & {memory_text} & {timeout_text} \\\\"
        )

    lines += [r"  \hline", r"\end{tabular}"]
    with open(OUTPUT_TEX, "w") as handle:
        handle.write("\n".join(lines) + "\n")


def main():
    summaries = summarize(read_all_rows())
    write_csv(summaries)
    write_tex(summaries)
    print(f"CSV written to: {OUTPUT_CSV}")
    print(f"LaTeX table written to: {OUTPUT_TEX}")


if __name__ == "__main__":
    main()
