#!/usr/bin/env python3
"""Generate img/inputCounts.tex from the controlled benchmark results.

The output preserves the table structure used by the manuscript. Input-size
statistics are read from one representative grammar variant per source corpus.
Timeouts are counted from every variant named in that displayed row.
"""

import csv
import os
import statistics
from collections import Counter


from artifact_paths import RESULT_ROOT, IMG_DIR
RESULTS_DIR = os.path.join(RESULT_ROOT, "benchmark_csv")
OUTPUT_TEX = os.path.join(IMG_DIR, "inputCounts.tex")

PARSERS = ["GLL", "RNGLR", "BRNGLR", "Leo"]

# (display cell, representative file, files whose timeouts belong to the row,
#  add the manuscript's ambiguity-only dagger to GLL)
ROWS = [
    (r"\GANSIC", "benchmark_ansi_c.csv", ["benchmark_ansi_c.csv"], False),
    (r"\GBool", "benchmark_bool.csv", ["benchmark_bool.csv"], False),
    (r"\GCPP", "benchmark_cpp.csv", ["benchmark_cpp.csv"], False),
    (r"\GCSS", "benchmark_css.csv", ["benchmark_css.csv"], False),
    (
        r"\GExprLLA, \GExprLR, \GExprRR, \GExprAmbig",
        "benchmark_calc.csv",
        [
            "benchmark_calc_ll1.csv",
            "benchmark_calc.csv",
            "benchmark_expr.csv",
            "benchmark_expr_ambi.csv",
        ],
        True,
    ),
    (r"\GHTML", "benchmark_html.csv", ["benchmark_html.csv"], False),
    (r"\GJava", "benchmark_java.csv", ["benchmark_java.csv"], False),
    (
        r"\GJSONLLA, \GJSONRR, \GJSONLR, \GJSONAmbig",
        "benchmark_json.csv",
        [
            "benchmark_json_ll1.csv",
            "benchmark_json.csv",
            "benchmark_json_lr.csv",
            "benchmark_json_ambi.csv",
        ],
        False,
    ),
    (r"\GPascal", "benchmark_pascal.csv", ["benchmark_pascal.csv"], False),
    (
        r"\GSExprLLA, \GSExpression",
        "benchmark_sexp.csv",
        ["benchmark_sexp_ll1.csv", "benchmark_sexp.csv"],
        False,
    ),
    (r"\GShell", "benchmark_shell.csv", ["benchmark_shell.csv"], False),
    (r"\GSQL", "benchmark_sql.csv", ["benchmark_sql.csv"], False),
    (r"\GTinyC", "benchmark_tinyc.csv", ["benchmark_tinyc.csv"], False),
    (
        r"\GTinyCLRA",
        "benchmark_tinyc_lr.csv",
        ["benchmark_tinyc_lr.csv"],
        False,
    ),
    (
        r"\GTinyPascal",
        "benchmark_tinypascal.csv",
        ["benchmark_tinypascal.csv"],
        False,
    ),
]


def read_rows(filename):
    with open(os.path.join(RESULTS_DIR, filename), newline="") as handle:
        return list(csv.DictReader(handle))


def representative_lengths(filename):
    rows = [row for row in read_rows(filename) if row["parser"] == "Leo"]
    if not rows:
        raise ValueError(f"{filename}: no Leo rows available for input statistics")
    return [int(row["input_length"]) for row in rows]


def timeout_counts(filenames):
    counts = Counter()
    for filename in filenames:
        for row in read_rows(filename):
            if row["parser"] in PARSERS and row.get("status") == "TIMEOUT":
                counts[row["parser"]] += 1
    return counts


def fmt_stat(value):
    return f"{value:,.1f}".replace(",", "{,}")


def fmt_int(value):
    return f"{value:,}".replace(",", "{,}")


def fmt_timeout(value, dagger=False):
    if value == 0:
        return "---"
    suffix = r"$^\dagger$" if dagger else ""
    return f"{value}{suffix}"


def main():
    lines = [
        r"% Generated by script/make_input_counts_table.py -- do not edit by hand.",
        r"% Caption and label live in the main .tex file.",
        r"\begin{tabular}{|l|r|r|r|r|r|r|r|r|}",
        r"  \hline",
        r"  \multirow{2}{*}{\textbf{Language}} & \multirow{2}{*}{\textbf{Mean}} & \multirow{2}{*}{\textbf{Stdev}} & \multirow{2}{*}{\textbf{Min}} & \multirow{2}{*}{\textbf{Max}} & \multicolumn{4}{c|}{\textbf{Timeouts}} \\",
        r"  \cline{6-9}",
        r"  & & & & & \textbf{GLL} & \textbf{RNGLR} & \textbf{BRNGLR} & \textbf{Earley} \\",
        r"  \hline\hline",
    ]

    for display, representative, timeout_files, gll_dagger in ROWS:
        lengths = representative_lengths(representative)
        counts = timeout_counts(timeout_files)
        cells = [
            display,
            fmt_stat(statistics.mean(lengths)),
            fmt_stat(statistics.stdev(lengths)),
            fmt_int(min(lengths)),
            fmt_int(max(lengths)),
            fmt_timeout(counts["GLL"], gll_dagger),
            fmt_timeout(counts["RNGLR"]),
            fmt_timeout(counts["BRNGLR"]),
            fmt_timeout(counts["Leo"]),
        ]
        lines.append("  " + " & ".join(cells) + r" \\")

    lines += [r"  \hline", r"\end{tabular}"]
    os.makedirs(os.path.dirname(OUTPUT_TEX), exist_ok=True)
    with open(OUTPUT_TEX, "w") as handle:
        handle.write("\n".join(lines) + "\n")
    print(f"LaTeX table written to: {OUTPUT_TEX}")


if __name__ == "__main__":
    main()
